/*
 * Continous Food Delievery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.continuousfooddelivery;

import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for CartApi
 */
@Ignore
public class CartApiTest {

    private final CartApi api = new CartApi();

    
    /**
     * Add a menu item a cart
     *
     * Creates a new item in the cart. Duplicates are allowed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addCartItemTest() throws ApiException {
        MenuItem menuItem = null;
                api.addCartItem(menuItem);
        // TODO: test validations
    }
    
    /**
     * Remove item from cart
     *
     * The item must be in the cart. If multiple of same item, call this twice 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCartItemTest() throws ApiException {
        Integer itemId = null;
                api.deleteCartItem(itemId);
        // TODO: test validations
    }
    
    /**
     * List all cart items
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCartTest() throws ApiException {
        Integer limit = null;
                List<MenuItem> response = api.listCart(limit);
        // TODO: test validations
    }
    
}
