/*
 * Continous Food Delievery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.continuousfooddelivery;

import java.io.File;
import com.circleci.continuousfooddelivery.InlineObject;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for ImageApi
 */
@Ignore
public class ImageApiTest {

    private final ImageApi api = new ImageApi();

    
    /**
     * Add an image to the restaraunt
     *
     * Creates an image. Duplicates are allowed. Returns the image id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addImageTest() throws ApiException {
        InlineObject inlineObject = null;
                InlineResponse200 response = api.addImage(inlineObject);
        // TODO: test validations
    }
    
    /**
     * Remove image
     *
     * The imageId must exist 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteImageTest() throws ApiException {
        Integer imageId = null;
                api.deleteImage(imageId);
        // TODO: test validations
    }
    
    /**
     * Get image
     *
     * Returns the image as image/png 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getImageTest() throws ApiException {
        Integer imageId = null;
                File response = api.getImage(imageId);
        // TODO: test validations
    }
    
}
