/*
 * Continous Food Delievery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.continuousfooddelivery;

import org.junit.Test;


/**
 * Model tests for InlineResponse200
 */
public class InlineResponse200Test {
    private final InlineResponse200 model = new InlineResponse200();

    /**
     * Model tests for InlineResponse200
     */
    @Test
    public void testInlineResponse200() {
        // TODO: test InlineResponse200
    }

    /**
     * Test the property 'imageId'
     */
    @Test
    public void imageIdTest() {
        // TODO: test imageId
    }

}
