/*
 * Continous Food Delievery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.continuousfooddelivery;

import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for MenuApi
 */
@Ignore
public class MenuApiTest {

    private final MenuApi api = new MenuApi();

    
    /**
     * Create a menu item
     *
     * Creates a new item in the menu. Duplicates are allowed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addMenuItemTest() throws ApiException {
        MenuItem menuItem = null;
                api.addMenuItem(menuItem);
        // TODO: test validations
    }
    
    /**
     * List all menu items
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMenuTest() throws ApiException {
        Integer limit = null;
                List<MenuItem> response = api.listMenu(limit);
        // TODO: test validations
    }
    
    /**
     * Info for a specific menu item
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showMenuItemByIdTest() throws ApiException {
        String itemId = null;
                MenuItem response = api.showMenuItemById(itemId);
        // TODO: test validations
    }
    
}
